; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.16 on Tue Oct 24 2023 12:21:46 GMT-0500 (Central Daylight Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


